# Generated by Django 6.0.2 on 2026-05-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to='core.hospital')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='UrgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.hospital')),
            ],
            options={
                'verbose_name': 'Urgent Request',
                'verbose_name_plural': 'Urgent Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='interested', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='donations.urgentrequest')),
            ],
            options={
                'verbose_name': 'Appeal Response',
                'verbose_name_plural': 'Appeal Responses',
                'ordering': ['-response_date'],
                'unique_together': {('donor', 'request')},
            },
        ),
    ]
