# Generated by Django 6.0.2 on 2026-04-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('quantite', models.PositiveIntegerField()),
                ('delai', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.hopital')),
            ],
            options={
                'verbose_name': 'Demande Urgente',
                'verbose_name_plural': 'Demandes Urgentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='core.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_recus', to='core.hopital')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don'],
            },
        ),
        migrations.CreateModel(
            name='ReponseAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('interested', 'Interested'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='interested', max_length=20)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='donations.demandeurgente')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.donneur')),
            ],
            options={
                'verbose_name': 'Reponse Appel',
                'verbose_name_plural': 'Reponses Appel',
                'ordering': ['-date_reponse'],
                'unique_together': {('donneur', 'demande')},
            },
        ),
    ]
