# Generated by Django 6.0.2 on 2026-04-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('groupes_cibles', models.CharField(max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='core.hopital')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.TimeField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='hospitals.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='core.donneur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('campagne', 'donneur')},
            },
        ),
    ]
