# Generated by Django 6.0.2 on 2026-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='groupes_cibles',
            field=models.JSONField(default=list),
        ),
    ]
